FROM node:23

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

RUN npm run build

RUN apt-get update && apt-get install -y iproute2 iputils-ping && rm -rf /var/lib/apt/lists/*

COPY entrypoint-server.sh /entrypoint-server.sh
RUN chmod +x /entrypoint-server.sh

ENTRYPOINT ["/entrypoint-server.sh"]
